[package]
name = "memegenerator-backend"
version = "1.0.0"
edition = "2024"

[dependencies]
actix-web = "4.11"
actix-cors = "0.7.1"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"

base64 = "0.22"
rand = "0.9"

env_logger = "0.11"
